### ISSUE TITLE
Binary is outdated/not installed correctly?

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-server#10]
When using the single-command installer line:

```
curl https://raw.githubusercontent.com/intercity/intercity-server/master/scripts/installer | bash
```

I do not get the question if I want a custom port. I tested it 5 minutes ago (my Docker install is still running) and this is tested on a clean Amsterdam DigitalOcean Ubuntu 16.04 droplet. Perhaps the binary is not updated correctly?

Here's the top output from my `/var/lib/intercity-server install` command:

```
root@michiels:~# /var/intercity-cli/intercity-server install
What is the hostname? (e.g.: intercity.example.com)
michiels.intercity.io
Hostname is set to michiels.intercity.io
1. yes
2. no
Do you want to use LetsEncrypt for SSL?
IMPORTANT: The hostname should be public and reachable for the LetsEncrypt servers.
The SSL certificate can't be generated if LetsEncrypt can't reach the domain!
no
---- Installing docker
2016-09-19 08:56:05 URL:https://get.docker.com/ [15330/15330] -> "-" [1]
modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-36-generic

```

**Comment by michiels** [comment]
Just some extra information, when editing `/var/intercity-cli/lib/app/lib/intercity_server/installer.rb` there is no code about custom port settings present. It seems that this code does not reflect the latest version.

**Comment by michiels** [comment]
One more iteration of research. The targz on https://github.com/intercity/intercity.io/blob/master/downloads/linux_x86_64/intercity-server-0.2.0-linux-x86_64.tar.gz does not contain the custom port code either.

@jvanbaarsen Shall I update it?

**Comment by jvanbaarsen** [comment]
@michiels This is extremly weird. Since I did check that last time. :/ Let me push it once more.

**Comment by michiels** [comment]
@jvanbaarsen Okay, perhaps push it as 0.2.1 so people that already installed the current "broken" version will automatically install a new version? Or doesn't the installer work that way yet.

**Comment by jvanbaarsen** [comment]
@michiels Does not work that way. I did push the version to intercity.io. But forgot to push it to GH. I;ll push to prod again as well

**Comment by jvanbaarsen** [comment]
@michiels Can you try one more time with the installer? (Just the one from intercity.io)

**Comment by michiels** [comment]
@jvanbaarsen Ok, do I need to clean up my server? Or can I just re-run it?

**Comment by jvanbaarsen** [comment]
@michiels run `rm -rf /var/intercity-server` and install again

**Comment by michiels** [comment]
@jvanbaarsen I guess I have to remove my IC installation first, let me do that.

**Comment by michiels** [comment]
@jvanbaarsen Seems to work! The installer at least shows me the question now :)

**Comment by jvanbaarsen** [comment]
@michiels Perfect!

**Comment by michiels** [comment]
@jvanbaarsen Please don't forget to commit/PR it to master so this mistake doesn't happen again :D

**Comment by jvanbaarsen** [comment]
@michiels I already did :-) Can we have the intercity.io repo release master to production automaticly? 💃

**Comment by michiels** [comment]
@jvanbaarsen Cool! Jep I think so, let me check if I can add codeship

**Comment by jvanbaarsen** [comment]
:+1:
