### ISSUE TITLE
Question/Doc update: Server reboot needed?

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-server#6]
I see that in the installation script a new kernal image and headers are installed. Is it also necessary to actually run that kernel? (because that will require a reboot) or are those packages installed, just for some file dependencies?

**Comment by jvanbaarsen** [comment]
@michiels Can you point me to that part?

**Comment by michiels** [comment]
@jvanbaarsen when `intercity-server install` is at this line:

```
root@ubuntu-1gb-ams2-01:~# intercity-server install
What is the hostname? (e.g.: intercity.example.com)
michiel.intercity.io
Hostname is set to michiel.intercity.io
1. yes
2. no
Do you want to use LetsEncrypt for SSL?
IMPORTANT: The hostname should be public and reachable for the LetsEncrypt servers.
The SSL certificate can't be generated if LetsEncrypt can't reach the domain!
no
---- Installing docker
2016-08-29 19:01:39 URL:https://get.docker.com/ [15330/15330] -> "-" [1]
modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-34-generic
+ sh -c sleep 3; apt-get update
+ sh -c sleep 3; apt-get install -y -q linux-image-extra-4.4.0-34-generic linux-image-extra-virtual
```

I think that means that it's installing extra kernel functionality. But I think kernel functionality is never used when you don't reboot your server. But maybe I'm missing something. Also you get that `modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-34-generic` error, seems like something is missing in the kernel.

Are these install steps based on Docker installation manual for Ubuntu somewhere?

**Comment by michiels** [comment]
Ah, I see that this is based on the https://get.docker.com script. In that script I do see the check for aufs and installing extra kernel modules, but not instructions to reboot. So this must be fine :)

**Comment by jvanbaarsen** [comment]
@michiels 👍 Closing this issue
